apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: entities
  name: entities
spec:
  revisionHistoryLimit: 5
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: entities
    spec:
      containers:
      - name: entities
        image: slisson/webmps-entities:201912191127
        imagePullPolicy: IfNotPresent
        env:
        - name: MODEL_URI
          value: http://model:28101/
        ports:
        - containerPort: 33333
        - containerPort: 5071
          name: "jvm-debug"
        volumeMounts:
          - name: modelsecret
            mountPath: /secrets/modelsecret
            readOnly: true
        resources: 
          requests:
            memory: "2.0Gi"
            cpu: "0.8"
          limits:
            memory: "2.5Gi"
            cpu: "1.5"
        readinessProbe:
          httpGet:
            path: /health/check
            port: 33333
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /health/check
            port: 33333
          initialDelaySeconds: 120
          periodSeconds: 20
          timeoutSeconds: 10
      restartPolicy: Always
      volumes:
        - name: modelsecret
          secret:
            secretName: modelsecret
status: {}
