apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "modelix.fullname" . }}-ingress"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    {{ if and (not .Values.ingress.tls.crt) (not .Values.ingress.certSecret) }}
    # self-signed certificate. Allow http to avoid certificate errors.
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{ end }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "{{ .Values.ingress.hostname }}"
    {{ if not .Values.ingress.certSecret }}
    secretName: "{{ include "modelix.fullname" . }}-tls-secret"
    {{ else }}
    secretName: "{{ .Values.ingress.certSecret }}"
    {{ end }}
  rules:
    - host: "{{ .Values.ingress.hostname }}"
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: "{{ include "modelix.fullname" . }}-keycloak"
                port:
                  number: 8080
            path: /(resources|admin|js|realms)/.*
          - pathType: Prefix
            backend:
              service:
                name: "{{ include "modelix.fullname" . }}-oauth"
                port:
                  number: 4180
            path: /

