apiVersion: v1
kind: Service
metadata:
  labels:
    component: workspace-manager
    {{- include "modelix.labels" . | nindent 4 }}
  name: "{{ include "modelix.fullname" . }}-workspace-manager"
spec:
  type: NodePort
  ports:
  - name: "28104"
    port: 28104
    targetPort: 28104
  - name: "debug"
    port: 5071
    targetPort: 5071
  selector:
    component: workspace-manager
    {{- include "modelix.selectorLabels" . | nindent 4 }}
