{{- if .Values.workspaces.enabled  -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: workspace-manager
    {{- include "modelix.labels" . | nindent 4 }}
  name: "{{ include "modelix.fullname" . }}-workspace-manager"
spec:
  revisionHistoryLimit: 5
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      component: workspace-manager
      {{- include "modelix.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: workspace-manager
        {{- include "modelix.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: "{{ include "modelix.serviceAccountName" . }}"
      containers:
      - env:
          - name: model_server_url
            value: http://{{ include "modelix.fullname" . }}-model:28101/
          - name: "KUBERNETES_NAMESPACE"
            value: {{ .Release.Namespace }}
          - name: "WORKSPACE_JOB_IMAGE_NAME"
            value: "{{ .Values.dockerProxy.prefix }}modelix/workspace-job"
          - name: "WORKSPACE_JOB_IMAGE_VERSION"
            value: "{{ .Values.imageTags.wsJob | default .Chart.AppVersion }}"
          - name: "KUBERNETES_PREFIX"
            value: "{{ include "modelix.fullname" . }}-"
          {{- include "modelix.keycloakEnv" . | nindent 10 }}
        image: "{{ .Values.dockerProxy.prefix }}modelix/modelix-workspace-manager:{{ .Values.imageTags.wsManager | default .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        name: workspace-manager
        ports:
        - containerPort: 28104
        - containerPort: 5071
          name: "jvm-debug"
        resources: 
          requests:
            memory: "{{ .Values.workspaces.manager.memory | default "600Mi" }}""
            cpu: "0.1"
          limits:
            memory: "{{ .Values.workspaces.manager.memory | default "600Mi" }}"
            cpu: "1.0"
        readinessProbe:
          httpGet:
            path: /health
            port: 28104
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 28104
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
        volumeMounts:
          - mountPath: "/workspace-manager/modelix-workspaces/uploads"
            name: "{{ include "modelix.fullname" . }}-workspace-uploads"
          - name: "{{ include "modelix.fullname" . }}-workspace-secret"
            mountPath: /secrets/workspacesecret/workspace-credentials-key.txt
            readOnly: true
      restartPolicy: Always
      volumes:
        - name: "{{ include "modelix.fullname" . }}-workspace-uploads"
          persistentVolumeClaim:
            claimName: "{{ include "modelix.fullname" . }}-workspace-uploads"
        - name: "{{ include "modelix.fullname" . }}-workspace-secret"
          secret:
            secretName: "{{ include "modelix.fullname" . }}-workspace-secret"
      {{- include "modelix.pullSecret" . | nindent 6 }}
{{- end -}}
