imageTags:
  db: ""
  instancesManager: ""
  proxy: ""
  wsClient: ""
  wsManager: ""
  keycloak: ""
ingress:
  hostname: "localhost"
ingress-nginx:
  enabled: true
keycloak:
  loglevel: "warn"
  debug: true
workspaces:
  enabled: true