name: ModelClient

on:
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-build-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-build-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          gradle-build-
          gradle-
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Assemble
      run: cd model-client && ../gradlew compileKotlinJs compileKotlinJvm

  jvmTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-jvmTest-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-jvmTest-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          gradle-jvmTest-
          gradle-
    - name: Run JVM unit tests
      run: cd model-client && ../gradlew jvmTest

  jsTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-jsTest-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-jsTest-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          gradle-jsTest-
          gradle-
    - name: Run JS unit tests
      run: cd model-client && ../gradlew jsTest      

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-lint-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-lint-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          gradle-lint-
          gradle-
    - name: Run linter
      run: cd model-client && ../gradlew ktlintCheck
